// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function SaveTools(arg1:Array<settings.ToolGroup>):Promise<void>;

export function Tools():Promise<Array<settings.ToolGroup>>;
