// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserData(arg1) {
  return window['go']['settings']['Settings']['GetUserData'](arg1);
}

export function SetUerData(arg1, arg2) {
  return window['go']['settings']['Settings']['SetUerData'](arg1, arg2);
}
