// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveTools(arg1) {
  return window['go']['settings']['Settings']['SaveTools'](arg1);
}

export function Tools() {
  return window['go']['settings']['Settings']['Tools']();
}
